export const CardOnGameBoard = [
  [
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined, url: 'gray_back' },
    { value: 2, face: '2', suit: 'S', status: undefined, url: '2S' },
    { value: 3, face: '3', suit: 'S', status: undefined, url: '3S' },
    { value: 4, face: '4', suit: 'S', status: undefined, url: '4S' },
    { value: 5, face: '5', suit: 'S', status: undefined, url: '5S' },
    { value: 6, face: '6', suit: 'S', status: undefined, url: '6S' },
    { value: 7, face: '7', suit: 'S', status: undefined, url: '7S' },
    { value: 8, face: '8', suit: 'S', status: undefined, url: '8S' },
    { value: 9, face: '9', suit: 'S', status: undefined, url: '9S' },
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined, url: 'gray_back' },
  ],
  [
    { value: 6, face: '6', suit: 'C', status: undefined, url: '6C' },
    { value: 5, face: '5', suit: 'C', status: undefined, url: '5C' },
    { value: 4, face: '4', suit: 'C', status: undefined, url: '4C' },
    { value: 3, face: '3', suit: 'C', status: undefined, url: '3C' },
    { value: 2, face: '2', suit: 'C', status: undefined, url: '2C' },
    { value: 14, face: 'A', suit: 'H', status: undefined, url: 'AH' },
    { value: 13, face: 'K', suit: 'H', status: undefined, url: 'KH' },
    { value: 12, face: 'Q', suit: 'H', status: undefined, url: 'QH' },
    { value: 10, face: '10', suit: 'H', status: undefined, url: '10H' },
    { value: 10, face: '10', suit: 'S', status: undefined, url: '10S' },
  ],
  [
    { value: 7, face: '7', suit: 'C', status: undefined, url: '7C' },
    { value: 14, face: 'A', suit: 'S', status: undefined, url: 'AS' },
    { value: 2, face: '2', suit: 'D', status: undefined, url: '2D' },
    { value: 3, face: '3', suit: 'D', status: undefined, url: '3D' },
    { value: 4, face: '4', suit: 'D', status: undefined, url: '4D' },
    { value: 5, face: '5', suit: 'D', status: undefined, url: '5D' },
    { value: 6, face: '6', suit: 'D', status: undefined, url: '6D' },
    { value: 7, face: '7', suit: 'D', status: undefined, url: '7D' },
    { value: 9, face: '9', suit: 'H', status: undefined, url: '9H' },
    { value: 12, face: 'Q', suit: 'S', status: undefined, url: 'QS' },
  ],
  [
    { value: 8, face: '8', suit: 'C', status: undefined, url: '8C' },
    { value: 13, face: 'K', suit: 'S', status: undefined, url: 'KS' },
    { value: 6, face: '6', suit: 'C', status: undefined, url: '6C' },
    { value: 5, face: '5', suit: 'C', status: undefined, url: '5C' },
    { value: 4, face: '4', suit: 'C', status: undefined, url: '4C' },
    { value: 3, face: '3', suit: 'C', status: undefined, url: '3C' },
    { value: 2, face: '2', suit: 'C', status: undefined, url: '2C' },
    { value: 8, face: '8', suit: 'D', status: undefined, url: '8D' },
    { value: 8, face: '8', suit: 'H', status: undefined, url: '8H' },
    { value: 13, face: 'K', suit: 'S', status: undefined, url: 'KS' },
  ],
  [
    { value: 9, face: '9', suit: 'C', status: undefined, url: '9C' },
    { value: 12, face: 'Q', suit: 'S', status: undefined, url: 'QS' },
    { value: 7, face: '7', suit: 'C', status: undefined, url: '7C' },
    { value: 6, face: '6', suit: 'H', status: undefined, url: '6H' },
    { value: 5, face: '5', suit: 'H', status: undefined, url: '5H' },
    { value: 4, face: '4', suit: 'H', status: undefined, url: '4H' },
    { value: 14, face: 'A', suit: 'H', status: undefined, url: 'AH' },
    { value: 9, face: '9', suit: 'D', status: undefined, url: '9D' },
    { value: 7, face: '7', suit: 'H', status: undefined, url: '7H' },
    { value: 14, face: 'A', suit: 'S', status: undefined, url: 'AS' },
  ],
  [
    { value: 10, face: '10', suit: 'C', status: undefined, url: '10C' },
    { value: 10, face: '10', suit: 'S', status: undefined, url: '10S' },
    { value: 8, face: '8', suit: 'C', status: undefined, url: '8C' },
    { value: 7, face: '7', suit: 'H', status: undefined, url: '7H' },
    { value: 2, face: '2', suit: 'H', status: undefined, url: '2H' },
    { value: 3, face: '3', suit: 'H', status: undefined, url: '3H' },
    { value: 13, face: 'K', suit: 'H', status: undefined, url: 'KH' },
    { value: 10, face: '10', suit: 'D', status: undefined, url: '10D' },
    { value: 6, face: '6', suit: 'H', status: undefined, url: '6H' },
    { value: 2, face: '2', suit: 'D', status: undefined, url: '2D' },
  ],
  [
    { value: 12, face: 'Q', suit: 'C', status: undefined, url: 'QC' },
    { value: 9, face: '9', suit: 'S', status: undefined, url: '9S' },
    { value: 9, face: '9', suit: 'C', status: undefined, url: '9C' },
    { value: 8, face: '8', suit: 'H', status: undefined, url: '8H' },
    { value: 9, face: '9', suit: 'H', status: undefined, url: '9H' },
    { value: 10, face: '10', suit: 'H', status: undefined, url: '10H' },
    { value: 12, face: 'Q', suit: 'H', status: undefined, url: 'QH' },
    { value: 12, face: 'Q', suit: 'D', status: undefined, url: 'QD' },
    { value: 5, face: '5', suit: 'H', status: undefined, url: '5H' },
    { value: 3, face: '3', suit: 'D', status: undefined, url: '3D' },
  ],
  [
    { value: 13, face: 'K', suit: 'C', status: undefined, url: 'KC' },
    { value: 8, face: '8', suit: 'S', status: undefined, url: '8S' },
    { value: 10, face: '10', suit: 'C', status: undefined, url: '10C' },
    { value: 12, face: 'Q', suit: 'C', status: undefined, url: 'QC' },
    { value: 13, face: 'K', suit: 'C', status: undefined, url: 'KC' },
    { value: 14, face: 'A', suit: 'C', status: undefined, url: 'AC' },
    { value: 14, face: 'A', suit: 'D', status: undefined, url: 'AD' },
    { value: 13, face: 'K', suit: 'D', status: undefined, url: 'KD' },
    { value: 4, face: '4', suit: 'H', status: undefined, url: '4H' },
    { value: 4, face: '4', suit: 'D', status: undefined, url: '4D' },
  ],
  [
    { value: 14, face: 'A', suit: 'C', status: undefined, url: 'AC' },
    { value: 7, face: '7', suit: 'S', status: undefined, url: '7S' },
    { value: 6, face: '6', suit: 'S', status: undefined, url: '6S' },
    { value: 5, face: '5', suit: 'S', status: undefined, url: '5S' },
    { value: 4, face: '4', suit: 'S', status: undefined, url: '4S' },
    { value: 3, face: '3', suit: 'S', status: undefined, url: '3S' },
    { value: 2, face: '2', suit: 'S', status: undefined, url: '2S' },
    { value: 2, face: '2', suit: 'H', status: undefined, url: '2H' },
    { value: 3, face: '3', suit: 'H', status: undefined, url: '3H' },
    { value: 5, face: '5', suit: 'D', status: undefined, url: '5D' },
  ],
  [
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined, url: 'gray_back' },
    { value: 14, face: 'A', suit: 'D', status: undefined, url: 'AD' },
    { value: 13, face: 'K', suit: 'D', status: undefined, url: 'KD' },
    { value: 12, face: 'Q', suit: 'D', status: undefined, url: 'QD' },
    { value: 10, face: '10', suit: 'D', status: undefined, url: '10D' },
    { value: 9, face: '9', suit: 'D', status: undefined, url: '9D' },
    { value: 8, face: '8', suit: 'D', status: undefined, url: '8D' },
    { value: 7, face: '7', suit: 'D', status: undefined, url: '7D' },
    { value: 6, face: '6', suit: 'D', status: undefined, url: '6D' },
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined, url: 'gray_back' },
  ],
]
