export const gameBoard = [
  [
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined },
    { value: 2, face: '2', suit: '♠', status: undefined },
    { value: 3, face: '3', suit: '♠', status: undefined },
    { value: 4, face: '4', suit: '♠', status: undefined },
    { value: 5, face: '5', suit: '♠', status: undefined },
    { value: 6, face: '6', suit: '♠', status: undefined },
    { value: 7, face: '7', suit: '♠', status: undefined },
    { value: 8, face: '8', suit: '♠', status: undefined },
    { value: 9, face: '9', suit: '♠', status: undefined },
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined },
  ],
  [
    { value: 6, face: '6', suit: '♣', status: undefined },
    { value: 5, face: '5', suit: '♣', status: undefined },
    { value: 4, face: '4', suit: '♣', status: undefined },
    { value: 3, face: '3', suit: '♣', status: undefined },
    { value: 2, face: '2', suit: '♣', status: undefined },
    { value: 14, face: 'A', suit: '♥', status: undefined },
    { value: 13, face: 'K', suit: '♥', status: undefined },
    { value: 12, face: 'Q', suit: '♥', status: undefined },
    { value: 10, face: '10', suit: '♥', status: undefined },
    { value: 10, face: '10', suit: '♠', status: undefined },
  ],
  [
    { value: 7, face: '7', suit: '♣', status: undefined },
    { value: 14, face: 'A', suit: '♠', status: undefined },
    { value: 2, face: '2', suit: '♦', status: undefined },
    { value: 3, face: '3', suit: '♦', status: undefined },
    { value: 4, face: '4', suit: '♦', status: undefined },
    { value: 5, face: '5', suit: '♦', status: undefined },
    { value: 6, face: '6', suit: '♦', status: undefined },
    { value: 7, face: '7', suit: '♦', status: undefined },
    { value: 9, face: '9', suit: '♥', status: undefined },
    { value: 12, face: 'Q', suit: '♠', status: undefined },
  ],
  [
    { value: 8, face: '8', suit: '♣', status: undefined },
    { value: 13, face: 'K', suit: '♠', status: undefined },
    { value: 6, face: '6', suit: '♣', status: undefined },
    { value: 5, face: '5', suit: '♣', status: undefined },
    { value: 4, face: '4', suit: '♣', status: undefined },
    { value: 3, face: '3', suit: '♣', status: undefined },
    { value: 2, face: '2', suit: '♣', status: undefined },
    { value: 8, face: '8', suit: '♦', status: undefined },
    { value: 8, face: '8', suit: '♥', status: undefined },
    { value: 13, face: 'K', suit: '♠', status: undefined },
  ],
  [
    { value: 9, face: '9', suit: '♣', status: undefined },
    { value: 12, face: 'Q', suit: '♠', status: undefined },
    { value: 7, face: '7', suit: '♣', status: undefined },
    { value: 6, face: '6', suit: '♥', status: undefined },
    { value: 5, face: '5', suit: '♥', status: undefined },
    { value: 4, face: '4', suit: '♥', status: undefined },
    { value: 14, face: 'A', suit: '♥', status: undefined },
    { value: 9, face: '9', suit: '♦', status: undefined },
    { value: 7, face: '7', suit: '♥', status: undefined },
    { value: 14, face: 'A', suit: '♠', status: undefined },
  ],
  [
    { value: 10, face: '10', suit: '♣', status: undefined },
    { value: 10, face: '10', suit: '♠', status: undefined },
    { value: 8, face: '8', suit: '♣', status: undefined },
    { value: 7, face: '7', suit: '♥', status: undefined },
    { value: 2, face: '2', suit: '♥', status: undefined },
    { value: 3, face: '3', suit: '♥', status: undefined },
    { value: 13, face: 'K', suit: '♥', status: undefined },
    { value: 10, face: '10', suit: '♦', status: undefined },
    { value: 6, face: '6', suit: '♥', status: undefined },
    { value: 2, face: '2', suit: '♦', status: undefined },
  ],
  [
    { value: 12, face: 'Q', suit: '♣', status: undefined },
    { value: 9, face: '9', suit: '♠', status: undefined },
    { value: 9, face: '9', suit: '♣', status: undefined },
    { value: 8, face: '8', suit: '♥', status: undefined },
    { value: 9, face: '9', suit: '♥', status: undefined },
    { value: 10, face: '10', suit: '♥', status: undefined },
    { value: 12, face: 'Q', suit: '♥', status: undefined },
    { value: 12, face: 'Q', suit: '♦', status: undefined },
    { value: 5, face: '5', suit: '♥', status: undefined },
    { value: 3, face: '3', suit: '♦', status: undefined },
  ],
  [
    { value: 13, face: 'K', suit: '♣', status: undefined },
    { value: 8, face: '8', suit: '♠', status: undefined },
    { value: 10, face: '10', suit: '♣', status: undefined },
    { value: 12, face: 'Q', suit: '♣', status: undefined },
    { value: 13, face: 'K', suit: '♣', status: undefined },
    { value: 14, face: 'A', suit: '♣', status: undefined },
    { value: 14, face: 'A', suit: '♦', status: undefined },
    { value: 13, face: 'K', suit: '♦', status: undefined },
    { value: 4, face: '4', suit: '♥', status: undefined },
    { value: 4, face: '4', suit: '♦', status: undefined },
  ],
  [
    { value: 14, face: 'A', suit: '♣', status: undefined },
    { value: 7, face: '7', suit: '♠', status: undefined },
    { value: 6, face: '6', suit: '♠', status: undefined },
    { value: 5, face: '5', suit: '♠', status: undefined },
    { value: 4, face: '4', suit: '♠', status: undefined },
    { value: 3, face: '3', suit: '♠', status: undefined },
    { value: 2, face: '2', suit: '♠', status: undefined },
    { value: 2, face: '2', suit: '♥', status: undefined },
    { value: 3, face: '3', suit: '♥', status: undefined },
    { value: 5, face: '5', suit: '♦', status: undefined },
  ],
  [
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined },
    { value: 14, face: 'A', suit: '♦', status: undefined },
    { value: 13, face: 'K', suit: '♦', status: undefined },
    { value: 12, face: 'Q', suit: '♦', status: undefined },
    { value: 10, face: '10', suit: '♦', status: undefined },
    { value: 9, face: '9', suit: '♦', status: undefined },
    { value: 8, face: '8', suit: '♦', status: undefined },
    { value: 7, face: '7', suit: '♦', status: undefined },
    { value: 6, face: '6', suit: '♦', status: undefined },
    { value: 0, face: 'Joker', suit: '♦♠♥♣', status: undefined },
  ],
]
