name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PGURI=postgres://postgres:secret@database/postgres" > .env
          echo "POSTGRES_PASSWORD=secret" >> .env
          echo "JWT_SECRET=secret" >> .env

      - name: Start Docker Compose Services
        run: |
          docker-compose -f compose.yaml up -d
          wget -O wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh -t 0 localhost:5173 &
          sleep 5

      - name: Build and Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          wait-on: 'http://localhost:5173'
          start: npm run dev
          config-file: cypress.config.cjs
