name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PGURI=postgres://postgres:secret@database/postgres" > .env
          echo "POSTGRES_PASSWORD=secret" >> .env
          echo "JWT_SECRET=secret" >> .env

      - name: Start Docker Compose Services
        run: docker-compose -f compose.yaml up -d

      -name: Start Application
        run: |
          cd frontend 
          npm install 
          npm run dev &
          sleep 10

      - name: Build and Cypress run
        run: |
          cd frontend 
          npx cypress run
